version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: inventorysystem-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: inventorysystem-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  test:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: inventorysystem-test
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    entrypoint: ["tail", "-f", "/dev/null"]  

    


volumes:
  postgres_data:
    driver: local

  